/**
 * Markdown exporter — renders workflow outputs as a structured Markdown document.
 */
import type { StepOutput } from '../executor/index.js';
import type { EvalResult } from '../eval/index.js';

export function toMarkdown(
  outputs: StepOutput[],
  evalResults: EvalResult[],
  options?: { title?: string; includeTokenStats?: boolean },
): string {
  const lines: string[] = [];
  const title = options?.title ?? 'Promptfile Output';
  const showStats = options?.includeTokenStats !== false;

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(
    `*Generated by [Promptfile](https://github.com/edujbarrios/promptfile) — ${new Date().toISOString()}*`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  for (let i = 0; i < outputs.length; i++) {
    const output = outputs[i];
    lines.push(`## Step ${i + 1} — \`${output.instruction}\``);
    lines.push('');
    lines.push(output.response.trim());
    lines.push('');

    if (showStats && output.tokens.total > 0) {
      lines.push(
        `> **Tokens:** ${output.tokens.prompt} prompt + ${output.tokens.completion} completion = **${output.tokens.total}** total`,
      );
      lines.push('');
    }
  }

  if (evalResults.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Evaluation');
    lines.push('');

    for (const result of evalResults) {
      const icon = result.passed ? '✅' : '❌';
      const score =
        result.score !== undefined ? ` *(${(result.score * 100).toFixed(0)}%)*` : '';
      lines.push(`- ${icon} **${result.check}**${score}: ${result.details}`);
    }

    lines.push('');
  }

  return lines.join('\n');
}
